name: Mon premier pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
  - name: Recuperer le code
    uses: actions/checkout@v4

  - name: Afficher les fichiers
    run: ls -la

  - name: Afficher un message
    run: echo "Mon premier pipeline fonctionne"
